name: Push to Multiple Self Hosted 1

on:
  push:
    branches:
      - multiple-self-hosted-1

jobs:
  push-to-multiple-server:
    name: Push to Multiple Self Hosted 1
    runs-on: [self-hosted, production-1]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'v18.18.0'
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          yarn global add pm2
      - name: Config env
        run: |
          cat << EOF > .env
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          EOF
      - name: Build Application
        run: yarn build
      - name: Run Application
        run: yarn start:prod
